services:
  db:
    image: mysql
    container_name: mysql_server
    restart: always
    ports: 
      - 3367:3367
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Vot
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backend
    ports: 
      - 5000:5000
    command: npm run dev
    depends_on: 
      - db

volumes:
  db_data:
