services:
  mysql-source:
    image: mysql:8.0
    container_name: mysql-source
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
        reservations:
          memory: 512M
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: Vot
    volumes:
      - mysql_source_data:/var/lib/mysql
      - ./database/source-my.cnf:/etc/mysql/my.cnf
      - ./database/queries/source:/docker-entrypoint-initdb.d 
    networks:
      - mysql_net
  
  mysql-replica:
    image: mysql:8.0
    container_name: mysql-replica
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
        reservations:
          memory: 512M
    ports: 
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: Vot
    volumes:
      - mysql_replica_data:/var/lib/mysql
      - ./database/replica-my.cnf:/etc/mysql/my.cnf
      - ./database/queries/replica:/docker-entrypoint-initdb.d 
    depends_on:
      - mysql-source
    networks:
      - mysql_net

networks:
  mysql_net:

volumes:
  mysql_source_data:
  mysql_replica_data:
